/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EnIndexRouteImport } from './routes/en/index'
import { Route as JaIndexRouteImport } from './routes/ja/index'
import { Route as KoIndexRouteImport } from './routes/ko/index'
import { Route as VsCleanmymacIndexRouteImport } from './routes/vs/cleanmymac/index'
import { Route as VsDaisydiskIndexRouteImport } from './routes/vs/daisydisk/index'
import { Route as VsMoleIndexRouteImport } from './routes/vs/mole/index'
import { Route as VsPuremacIndexRouteImport } from './routes/vs/puremac/index'
import { Route as EnVsCleanmymacIndexRouteImport } from './routes/en/vs/cleanmymac/index'
import { Route as EnVsDaisydiskIndexRouteImport } from './routes/en/vs/daisydisk/index'
import { Route as EnVsMoleIndexRouteImport } from './routes/en/vs/mole/index'
import { Route as EnVsPuremacIndexRouteImport } from './routes/en/vs/puremac/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnIndexRoute = EnIndexRouteImport.update({
  id: '/en/',
  path: '/en/',
  getParentRoute: () => rootRouteImport,
} as any)
const JaIndexRoute = JaIndexRouteImport.update({
  id: '/ja/',
  path: '/ja/',
  getParentRoute: () => rootRouteImport,
} as any)
const KoIndexRoute = KoIndexRouteImport.update({
  id: '/ko/',
  path: '/ko/',
  getParentRoute: () => rootRouteImport,
} as any)
const VsCleanmymacIndexRoute = VsCleanmymacIndexRouteImport.update({
  id: '/vs/cleanmymac/',
  path: '/vs/cleanmymac/',
  getParentRoute: () => rootRouteImport,
} as any)
const VsDaisydiskIndexRoute = VsDaisydiskIndexRouteImport.update({
  id: '/vs/daisydisk/',
  path: '/vs/daisydisk/',
  getParentRoute: () => rootRouteImport,
} as any)
const VsMoleIndexRoute = VsMoleIndexRouteImport.update({
  id: '/vs/mole/',
  path: '/vs/mole/',
  getParentRoute: () => rootRouteImport,
} as any)
const VsPuremacIndexRoute = VsPuremacIndexRouteImport.update({
  id: '/vs/puremac/',
  path: '/vs/puremac/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnVsCleanmymacIndexRoute = EnVsCleanmymacIndexRouteImport.update({
  id: '/en/vs/cleanmymac/',
  path: '/en/vs/cleanmymac/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnVsDaisydiskIndexRoute = EnVsDaisydiskIndexRouteImport.update({
  id: '/en/vs/daisydisk/',
  path: '/en/vs/daisydisk/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnVsMoleIndexRoute = EnVsMoleIndexRouteImport.update({
  id: '/en/vs/mole/',
  path: '/en/vs/mole/',
  getParentRoute: () => rootRouteImport,
} as any)
const EnVsPuremacIndexRoute = EnVsPuremacIndexRouteImport.update({
  id: '/en/vs/puremac/',
  path: '/en/vs/puremac/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/en/': typeof EnIndexRoute
  '/ja/': typeof JaIndexRoute
  '/ko/': typeof KoIndexRoute
  '/vs/cleanmymac/': typeof VsCleanmymacIndexRoute
  '/vs/daisydisk/': typeof VsDaisydiskIndexRoute
  '/vs/mole/': typeof VsMoleIndexRoute
  '/vs/puremac/': typeof VsPuremacIndexRoute
  '/en/vs/cleanmymac/': typeof EnVsCleanmymacIndexRoute
  '/en/vs/daisydisk/': typeof EnVsDaisydiskIndexRoute
  '/en/vs/mole/': typeof EnVsMoleIndexRoute
  '/en/vs/puremac/': typeof EnVsPuremacIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/en': typeof EnIndexRoute
  '/ja': typeof JaIndexRoute
  '/ko': typeof KoIndexRoute
  '/vs/cleanmymac': typeof VsCleanmymacIndexRoute
  '/vs/daisydisk': typeof VsDaisydiskIndexRoute
  '/vs/mole': typeof VsMoleIndexRoute
  '/vs/puremac': typeof VsPuremacIndexRoute
  '/en/vs/cleanmymac': typeof EnVsCleanmymacIndexRoute
  '/en/vs/daisydisk': typeof EnVsDaisydiskIndexRoute
  '/en/vs/mole': typeof EnVsMoleIndexRoute
  '/en/vs/puremac': typeof EnVsPuremacIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/en/': typeof EnIndexRoute
  '/ja/': typeof JaIndexRoute
  '/ko/': typeof KoIndexRoute
  '/vs/cleanmymac/': typeof VsCleanmymacIndexRoute
  '/vs/daisydisk/': typeof VsDaisydiskIndexRoute
  '/vs/mole/': typeof VsMoleIndexRoute
  '/vs/puremac/': typeof VsPuremacIndexRoute
  '/en/vs/cleanmymac/': typeof EnVsCleanmymacIndexRoute
  '/en/vs/daisydisk/': typeof EnVsDaisydiskIndexRoute
  '/en/vs/mole/': typeof EnVsMoleIndexRoute
  '/en/vs/puremac/': typeof EnVsPuremacIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/en/'
    | '/ja/'
    | '/ko/'
    | '/vs/cleanmymac/'
    | '/vs/daisydisk/'
    | '/vs/mole/'
    | '/vs/puremac/'
    | '/en/vs/cleanmymac/'
    | '/en/vs/daisydisk/'
    | '/en/vs/mole/'
    | '/en/vs/puremac/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/en'
    | '/ja'
    | '/ko'
    | '/vs/cleanmymac'
    | '/vs/daisydisk'
    | '/vs/mole'
    | '/vs/puremac'
    | '/en/vs/cleanmymac'
    | '/en/vs/daisydisk'
    | '/en/vs/mole'
    | '/en/vs/puremac'
  id:
    | '__root__'
    | '/'
    | '/en/'
    | '/ja/'
    | '/ko/'
    | '/vs/cleanmymac/'
    | '/vs/daisydisk/'
    | '/vs/mole/'
    | '/vs/puremac/'
    | '/en/vs/cleanmymac/'
    | '/en/vs/daisydisk/'
    | '/en/vs/mole/'
    | '/en/vs/puremac/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EnIndexRoute: typeof EnIndexRoute
  JaIndexRoute: typeof JaIndexRoute
  KoIndexRoute: typeof KoIndexRoute
  VsCleanmymacIndexRoute: typeof VsCleanmymacIndexRoute
  VsDaisydiskIndexRoute: typeof VsDaisydiskIndexRoute
  VsMoleIndexRoute: typeof VsMoleIndexRoute
  VsPuremacIndexRoute: typeof VsPuremacIndexRoute
  EnVsCleanmymacIndexRoute: typeof EnVsCleanmymacIndexRoute
  EnVsDaisydiskIndexRoute: typeof EnVsDaisydiskIndexRoute
  EnVsMoleIndexRoute: typeof EnVsMoleIndexRoute
  EnVsPuremacIndexRoute: typeof EnVsPuremacIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/': {
      id: '/en/'
      path: '/en'
      fullPath: '/en/'
      preLoaderRoute: typeof EnIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ja/': {
      id: '/ja/'
      path: '/ja'
      fullPath: '/ja/'
      preLoaderRoute: typeof JaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ko/': {
      id: '/ko/'
      path: '/ko'
      fullPath: '/ko/'
      preLoaderRoute: typeof KoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/cleanmymac/': {
      id: '/vs/cleanmymac/'
      path: '/vs/cleanmymac'
      fullPath: '/vs/cleanmymac/'
      preLoaderRoute: typeof VsCleanmymacIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/daisydisk/': {
      id: '/vs/daisydisk/'
      path: '/vs/daisydisk'
      fullPath: '/vs/daisydisk/'
      preLoaderRoute: typeof VsDaisydiskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/mole/': {
      id: '/vs/mole/'
      path: '/vs/mole'
      fullPath: '/vs/mole/'
      preLoaderRoute: typeof VsMoleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/puremac/': {
      id: '/vs/puremac/'
      path: '/vs/puremac'
      fullPath: '/vs/puremac/'
      preLoaderRoute: typeof VsPuremacIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/vs/cleanmymac/': {
      id: '/en/vs/cleanmymac/'
      path: '/en/vs/cleanmymac'
      fullPath: '/en/vs/cleanmymac/'
      preLoaderRoute: typeof EnVsCleanmymacIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/vs/daisydisk/': {
      id: '/en/vs/daisydisk/'
      path: '/en/vs/daisydisk'
      fullPath: '/en/vs/daisydisk/'
      preLoaderRoute: typeof EnVsDaisydiskIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/vs/mole/': {
      id: '/en/vs/mole/'
      path: '/en/vs/mole'
      fullPath: '/en/vs/mole/'
      preLoaderRoute: typeof EnVsMoleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/en/vs/puremac/': {
      id: '/en/vs/puremac/'
      path: '/en/vs/puremac'
      fullPath: '/en/vs/puremac/'
      preLoaderRoute: typeof EnVsPuremacIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EnIndexRoute: EnIndexRoute,
  JaIndexRoute: JaIndexRoute,
  KoIndexRoute: KoIndexRoute,
  VsCleanmymacIndexRoute: VsCleanmymacIndexRoute,
  VsDaisydiskIndexRoute: VsDaisydiskIndexRoute,
  VsMoleIndexRoute: VsMoleIndexRoute,
  VsPuremacIndexRoute: VsPuremacIndexRoute,
  EnVsCleanmymacIndexRoute: EnVsCleanmymacIndexRoute,
  EnVsDaisydiskIndexRoute: EnVsDaisydiskIndexRoute,
  EnVsMoleIndexRoute: EnVsMoleIndexRoute,
  EnVsPuremacIndexRoute: EnVsPuremacIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
